# Generated by Django 2.2.5 on 2019-09-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boast',
            field=models.BooleanField(default=False),
        ),
    ]
